### ISSUE TITLE
Implement tool to generate and extract training data for bbc_clean

### ISSUE THREAD

**Issue by frenchfaso** [open-ortho/bbc2digital#1]

**Comment by zgypa** [comment]
@frenchfaso : there are a few issues with the first run we did today:

1. The images produced are not only resized, but they are also rotated 180 degrees and mirrored.

![image](https://user-images.githubusercontent.com/5678168/228981654-c56447b6-a655-4711-80dd-9dcda0cf6cfa.png)

2. The tool crashed at 737/2477 with the following error:

```
[737/2477] SAVED: resized\B2408\Chest&Shoulder|B2408CSF04y06m.png
Traceback (most recent call last):
  File "C:\Users\afm\Downloads\bbc2digital-feature-1-bbc-clean-data-extractor\bbc2digital-feature-1-bbc-clean-data-extractor\bbc_clean\treerez\treerez.py", line 104, in <module>
    main(args)
  File "C:\Users\afm\Downloads\bbc2digital-feature-1-bbc-clean-data-extractor\bbc2digital-feature-1-bbc-clean-data-extractor\bbc_clean\treerez\treerez.py", line 85, in main
    convert(scans)
  File "C:\Users\afm\Downloads\bbc2digital-feature-1-bbc-clean-data-extractor\bbc2digital-feature-1-bbc-clean-data-extractor\bbc_clean\treerez\treerez.py", line 59, in convert
    cropped_np_im = autotrim(np_im)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\afm\Downloads\bbc2digital-feature-1-bbc-clean-data-extractor\bbc2digital-feature-1-bbc-clean-data-extractor\bbc_clean\treerez\treerez.py", line 46, in autotrim
    x0, y0 = coords.min(axis=0)
    ^^^^^^
ValueError: too many values to unpack (expected 2)

```

**Comment by frenchfaso** [comment]
Pillow had an issue handling the TIFF orientation tag https://github.com/python-pillow/Pillow/issues/4053 which should be resolved as of https://github.com/python-pillow/Pillow/pull/4063 
Any Chance windows file explorer simply ignores the TIFF orientation tag?
Have tried opening both files (original and resized) in a proper image viewer/editor?

For investigating the second issue I would need the TIFF that triggered the crash which should be B2408\Chest&Shoulder\B2408CSF04y06m.tif

**Comment by zgypa** [comment]
Yes, indeed. With Irfanview they look the same. I think this is done now. We should be able to merge back into develop.
